service: sample-events

frameworkVersion: '3'

plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  polly:
    handler: src/polly.handler
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - polly:SynthesizeSpeech
          - polly:StartSpeechSynthesisTask
        Resource: '*'
      - Effect: 'Allow'
        Action:
          - s3:GetObject
        Resource: 'arn:aws:s3:::nm-sample-events/todo/*'
      - Effect: 'Allow'
        Action:
          - s3:PutObject
        Resource: 'arn:aws:s3:::nm-sample-events-polly/*'
      

    events:
      - s3:
          bucket: nm-sample-events
          event: s3:ObjectCreated:*
          rules:
            - prefix: todo/
            - suffix: .txt

resources:
  Resources:
    PollyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: nm-sample-events-polly
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
